price-multiplier: 1.5

default-labels:
  - "Time: <1 Hour"
  - "Priority: 0 (Normal)"
payment-permit-max-price: 1000
comment-incentives: true
disable-analytics: true
max-concurrent-bounties: 2
command-settings:
  - name: "wallet"
    enabled: true
  - name: "assign"
    enabled: true
  - name: "query"
    enabled: true
promotion-comment: "\n<h6>If you enjoy the DevPool experience, please follow <a href='https://github.com/ubiquity'>Ubiquity on GitHub</a> and star <a href='https://github.com/ubiquity/devpool-directory'>this repo</a> to show your support. It helps a lot!</h6>"
register-wallet-with-verification: false
assistive-pricing: true
