name: Knip

on:
  pull_request:

permissions:
  checks: write

jobs:
  run-knip:
    runs-on: ubuntu-latest
    steps:
      - name: tree
        run: |
          pwd
          tree -L 3

      - name: Post the knip results
        uses: gitcoindev/knip-reporter@v1.2.1
        with:
          verbose: true
